//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface _TtC6IDEKit28IDETitledGroupingPlaceholder : NSObject
{
    // Error parsing type: , name: title
    // Error parsing type: , name: navigableItem_isMajorGroup
    // Error parsing type: , name: navigableItem_isEnabled
}

+ (BOOL)_showTitle;
- (CDUnknownBlockType).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) long long hash;
- (BOOL)isEqual:(id)arg1;
@property(nonatomic, readonly) BOOL navigableItem_isVisible;
@property(nonatomic) BOOL navigableItem_isEnabled; // @synthesize navigableItem_isEnabled;
@property(nonatomic) BOOL navigableItem_isMajorGroup; // @synthesize navigableItem_isMajorGroup;
@property(nonatomic, readonly) NSString *navigableItem_groupIdentifier;
@property(nonatomic, readonly) NSString *navigableItem_name;
- (id)initWithTitle:(id)arg1;
@property(nonatomic, readonly) NSString *title; // @synthesize title;

@end

