//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEKit/_TtC6IDEKit21RepositoriesOperation.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface _TtC6IDEKit15SearchOperation : _TtC6IDEKit21RepositoriesOperation
{
    // Error parsing type: , name: searchQuery
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithAccount:(id)arg1 pageCompletion:(CDUnknownBlockType)arg2 completion:(CDUnknownBlockType)arg3;
- (void)main;
- (id)initWithAccount:(id)arg1 searchQuery:(id)arg2 pageCompletion:(CDUnknownBlockType)arg3 completion:(CDUnknownBlockType)arg4;
@property(nonatomic, copy) NSString *searchQuery; // @synthesize searchQuery;

@end

