//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSOperation.h>

__attribute__((visibility("hidden")))
@interface _TtC6IDEKit21RepositoriesOperation : NSOperation
{
    // Error parsing type: , name: operation
    // Error parsing type: , name: account
    // Error parsing type: , name: _isCancelled
    // Error parsing type: , name: _isFinished
    // Error parsing type: , name: _isExecuting
    // Error parsing type: , name: pageCompletion
    // Error parsing type: , name: completion
}

+ (id)keyPathsForValuesAffectingIsCancelled;
+ (id)keyPathsForValuesAffectingIsExecuting;
+ (id)keyPathsForValuesAffectingIsFinished;
- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)cancel;
- (void)main;
- (id)initWithAccount:(id)arg1 pageCompletion:(CDUnknownBlockType)arg2 completion:(CDUnknownBlockType)arg3;
- (BOOL)isCancelled;
- (BOOL)isFinished;
- (BOOL)isExecuting;
@property(nonatomic) BOOL _isExecuting; // @synthesize _isExecuting;
@property(nonatomic) BOOL _isFinished; // @synthesize _isFinished;
@property(nonatomic) BOOL _isCancelled; // @synthesize _isCancelled;

// Remaining properties
@property(nonatomic, readonly) BOOL cancelled;
@property(nonatomic, readonly) BOOL executing;
@property(nonatomic, readonly) BOOL finished;

@end

