//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEFoundation/IDEActivityLogRecord.h>

@class NSImage;

@interface IDEActivityLogRecord (IDEActivityLogAdditions)
+ (id)keyPathsForValuesAffectingStatusImage;
+ (id)keyPathsForValuesAffectingNavigableItem_progressValue;
@property(readonly) NSImage *statusImage;
@property(readonly) long long navigableItem_progressValue;
@end

