//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSTableCellView.h>

@class IDEAccountPrefsEntitlementsIconsView;
@protocol DVTProvisioningProfile;

@interface IDEAccountPrefsDeveloperAccountProfileCellView : NSTableCellView
{
    IDEAccountPrefsEntitlementsIconsView *_iconsView;
}

@property(retain) IDEAccountPrefsEntitlementsIconsView *iconsView; // @synthesize iconsView=_iconsView;
- (void).cxx_destruct;
@property(retain) id <DVTProvisioningProfile> objectValue; // @dynamic objectValue;

@end

