//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEFoundation/IDEAlert.h>

@interface IDEAlert (IDEAlertUI)
+ (id)keyPathsForValuesAffectingTextColor;
- (id)textColor;
- (id)targettedWorkspaceWindowControllerForWorkspace:(id)arg1 withContext:(id)arg2;
- (id)targettedWorkspaceWindowControllerForWorkspace:(id)arg1;
@end

