//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEKit/IDEDistributionStepViewController.h>

@class NSProgressIndicator, NSString;

@interface IDEDistributionUploadStepViewController : IDEDistributionStepViewController
{
    NSProgressIndicator *_progressIndicator;
    double _progress;
    NSString *_message;
}

+ (BOOL)skipStepForContext:(id)arg1 assistantDirection:(int)arg2;
@property(copy) NSString *message; // @synthesize message=_message;
@property(nonatomic) double progress; // @synthesize progress=_progress;
@property(retain, nonatomic) NSProgressIndicator *progressIndicator; // @synthesize progressIndicator=_progressIndicator;
- (void).cxx_destruct;
- (void)viewDidInstall;
- (id)iTunesPlatformForArchive:(id)arg1 session:(id)arg2 error:(id *)arg3;
- (BOOL)canGoPrevious;
- (BOOL)canGoNext;
- (id)title;
- (id)nibName;

@end

