//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class DVTDeveloperAccount, NSString;

@interface IDEDistributionAccountIssue : NSObject
{
    BOOL _isLoginIssue;
    DVTDeveloperAccount *_account;
    NSString *_issue;
}

+ (id)loginIssueForAccount:(id)arg1;
+ (id)roleIssueForAccount:(id)arg1 issue:(id)arg2;
@property(nonatomic) BOOL isLoginIssue; // @synthesize isLoginIssue=_isLoginIssue;
@property(retain, nonatomic) NSString *issue; // @synthesize issue=_issue;
@property(retain, nonatomic) DVTDeveloperAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;

@end

