//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTKit/DVTLibraryController.h>

@class NSArray;

@interface IDEFileTemplatesLibrary : DVTLibraryController
{
    BOOL _isLibraryPopulated;
    NSArray *_orderedPlatformFamilies;
}

- (void).cxx_destruct;
- (void)populatePasteboard:(id)arg1 withAssets:(id)arg2;
- (void)primitiveInvalidate;
- (void)libraryDidLoad;
- (id)templateSections;
- (id)allValidPlatforms;
- (void)addLibraryGroupsIfNeeded;
- (id)platformIconForPlatformFamily:(id)arg1;
- (id)defaultPlatformIcon;

@end

