//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEFoundation/IDEFileReference.h>

@interface IDEFileReference (InspectorProperties)
+ (id)keyPathsForValuesAffectingIdeInspectedNilResolutionStrategyPlaceholder;
+ (id)keyPathsForValuesAffectingIdeInspectedRelativeLocationIsEditable;
+ (id)keyPathsForValuesAffectingIdeInspectedRelativeLocationContainingFolderPlaceholder;
+ (id)keyPathsForValuesAffectingIdeInspectedRelativeLocationPlaceholder;
+ (id)keyPathsForValuesAffectingIdeInspectedMessageForChoosingRelativeLocation;
+ (id)keyPathsForValuesAffectingIdeInspectedRelativeLocationShouldChooseDirectory;
+ (id)keyPathsForValuesAffectingIdeInspectedRelativeLocationShouldChooseFile;
+ (id)keyPathsForValuesAffectingIdeInspectedAssignedDataType;
+ (id)keyPathsForValuesAffectingIdeInspectedShowsFileTypePopUp;
+ (id)keyPathsForValuesAffectingIdeInspectedIsNameEditable;
- (id)ideInspectedNilResolutionStrategyPlaceholder;
- (BOOL)ideInspectedRelativeLocationIsEditable;
- (id)ideInspectedRelativeLocationContainingFolderPlaceholder;
- (id)ideInspectedRelativeLocationPlaceholder;
- (id)ideInspectedMessageForChoosingRelativeLocation;
- (BOOL)ideInspectedRelativeLocationShouldChooseDirectory;
- (BOOL)ideInspectedRelativeLocationShouldChooseFile;
- (id)ideInspectedAssetTagPlaceholder;
- (id)ideInspectedPossibleAssetTags;
- (void)setIdeInspectedAssignedDataType:(id)arg1;
- (id)ideInspectedAssignedDataType;
- (BOOL)ideInspectedShowsFileTypePopUp;
- (BOOL)ideInspectedIsNameEditable;
- (id)applicableInspectorsForCategory:(id)arg1 suggestion:(id)arg2;
@end

