//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEFoundation/IDEGroup.h>

@interface IDEGroup (InspectorProperties)
+ (id)keyPathsForValuesAffectingHandlesIdeInspectedCanClearRelativeLocation;
+ (id)keyPathsForValuesAffectingIdeInspectedIsNameEditable;
- (id)ideInspectedRelativeLocationContainingFolderPlaceholder;
- (id)ideInspectedRelativeLocationPlaceholder;
- (BOOL)ideInspectedCanClearRelativeLocation;
- (BOOL)ideInspectedRelativeLocationShouldChooseDirectory;
- (BOOL)ideInspectedRelativeLocationShouldChooseFile;
- (BOOL)ideInspectedIsNameEditable;
- (id)applicableInspectorsForCategory:(id)arg1 suggestion:(id)arg2;
@end

