//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

#import <IDEKit/DVTTableCellViewStatusView-Protocol.h>

@class NSArray, NSImage, NSStackView;

@interface IDEIssueStatusImageView : NSView <DVTTableCellViewStatusView>
{
    long long _currentRowSizeStyle;
    NSStackView *_stackView;
}

@property(retain, nonatomic) NSStackView *stackView; // @synthesize stackView=_stackView;
@property(nonatomic) long long currentRowSizeStyle; // @synthesize currentRowSizeStyle=_currentRowSizeStyle;
- (void).cxx_destruct;
- (void)rowSizeStyleDidChange:(long long)arg1;
- (void)updateIntrisicContentSize:(id)arg1;
@property(retain, nonatomic) NSArray *images;
@property(retain, nonatomic) NSImage *image;
- (id)init;

@end

