//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEKit/IDELaunchActionOptionViewController.h>

@class IDEScheme, NSMenu;

@interface IDEOpenGLESOptionsController : IDELaunchActionOptionViewController
{
    NSMenu *_menu;
    IDEScheme *_scheme;
}

+ (BOOL)availableForScheme:(id)arg1;
- (void).cxx_destruct;
- (void)primitiveInvalidate;
- (void)loadView;
- (id)initWithScheme:(id)arg1;

@end

