//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTFoundation/DVTDocumentLocation.h>

@class NSURL;

@interface IDETestReportActivityDocumentLocation : DVTDocumentLocation
{
    NSURL *_dataURL;
}

@property(retain, nonatomic) NSURL *dataURL; // @synthesize dataURL=_dataURL;
- (void).cxx_destruct;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (id)initWithDocumentURL:(id)arg1 timestamp:(id)arg2 activityDataURL:(id)arg3;

@end

