//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEKit/XCSLocalObject-Protocol.h>

@class IDEWorkspace, NSArray, NSString;

@protocol XCSLocalServiceProtocol <XCSLocalObject>
@property(readonly, nonatomic) NSArray *fetchedBots;
@property(readonly, nonatomic) BOOL isPerformingMaintenanceTask;
@property(readonly, nonatomic) NSString *lastCreatedBotID;
@property(readonly, nonatomic) NSString *identifier;
@property(readonly, nonatomic) long long accountReachability;
@property(readonly, nonatomic) NSString *name;
- (BOOL)enabled;
- (NSArray *)itemsFilteredToWorkspace:(IDEWorkspace *)arg1;
@end

