//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTFoundation/DVTInvalidation_NSObject.h>

@class DVTOperationGroup, NSString;

@interface _TtC13IDEFoundation28IDEStructureEditingProcedure : DVTInvalidation_NSObject
{
    // Error parsing type: , name: topLevelOperation
    // Error parsing type: , name: _mainThreadTimeSlicingQueue
}

- (CDUnknownBlockType).cxx_destruct;
- (void)startOperationOnQueue:(id)arg1 finalOperation:(id)arg2;
- (void)enqueue:(id)arg1;
@property(nonatomic, readonly) double progress;
@property(nonatomic, readonly) NSString *title;
- (void)primitiveInvalidate;
- (id)init;
@property(nonatomic, retain) DVTOperationGroup *topLevelOperation; // @synthesize topLevelOperation;

@end

