//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEFoundation/_TtC13IDEFoundation38IDEStructureEditingFileSystemOperation.h>

__attribute__((visibility("hidden")))
@interface _TtC13IDEFoundation46IDEStructureEditingFileSystemMoveCopyOperation : _TtC13IDEFoundation38IDEStructureEditingFileSystemOperation
{
}

- (id)performWithProcedure:(id)arg1;

@end

