//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <IDEFoundation/DVTSourceControlFingerprintManager-Protocol.h>

@class NSDictionary;

@interface _TtC13IDEFoundation31SourceControlFingerprintManager : NSObject <DVTSourceControlFingerprintManager>
{
    // Error parsing type: , name: _shouldLoadKnownHosts
    // Error parsing type: , name: _sourceControlManager
    // Error parsing type: , name: knownHosts
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)updateUserDefaults;
- (id)existingFingerprintForRepository:(id)arg1;
- (void)loadKnownHostsFromDictionary:(id)arg1;
- (id)existingFingerprintForHost:(id)arg1;
- (void)addKnownHost:(id)arg1 fingerprint:(id)arg2;
- (id)initWithShouldLoadKnownHosts:(BOOL)arg1 sourceControlManager:(id)arg2;
@property(nonatomic, copy) NSDictionary *knownHosts; // @synthesize knownHosts;

@end

