//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEFoundation/_TtC13IDEFoundation37IDEStructureEditingInsertingProcedure.h>

@class NSString;

@interface _TtC13IDEFoundation36IDEStructureEditingMoveCopyProcedure : _TtC13IDEFoundation37IDEStructureEditingInsertingProcedure
{
    // Error parsing type: , name: didShowSheet
    // Error parsing type: , name: shouldCopyFiles
    // Error parsing type: , name: shouldCreateBlueFoldersForDirectories
    // Error parsing type: , name: referenceCreationCompletionBlock
    // Error parsing type: , name: _targetApplierOperation
    // Error parsing type: , name: _initialIntentOverride
}

- (CDUnknownBlockType).cxx_destruct;
- (void)newReferencesCreatedWithReferences:(id)arg1;
@property(nonatomic, readonly) BOOL requiresUserInteraction;
- (void)startOperationOnQueue:(id)arg1 finalOperation:(id)arg2;
@property(nonatomic, readonly) NSString *title;
- (void)replan;
- (void)primitiveInvalidate;
@property(nonatomic, copy) CDUnknownBlockType referenceCreationCompletionBlock; // @synthesize referenceCreationCompletionBlock;
@property(nonatomic) BOOL shouldCreateBlueFoldersForDirectories; // @synthesize shouldCreateBlueFoldersForDirectories;
@property(nonatomic) BOOL shouldCopyFiles; // @synthesize shouldCopyFiles;
@property(nonatomic) BOOL didShowSheet; // @synthesize didShowSheet;

@end

