//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTFoundation/DVTOperation.h>

__attribute__((visibility("hidden")))
@interface _TtC13IDEFoundation28IDEStructureEditingOperation : DVTOperation
{
    // Error parsing type: , name: _procedure
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (id)performWithProcedure:(id)arg1;
- (void)main;
- (void)reportWithError:(id)arg1;
- (id)initWithProcedure:(id)arg1;

@end

