//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEFoundation/_TtC13IDEFoundation28IDEStructureEditingProcedure.h>

@interface _TtC13IDEFoundation35IDEStructureEditingPlannedProcedure : _TtC13IDEFoundation28IDEStructureEditingProcedure
{
    // Error parsing type: , name: topLevelItems
    // Error parsing type: , name: _masterPlans
    // Error parsing type: , name: _unplannedItemCount
    // Error parsing type: , name: _completed
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)newReferencesCreatedWithReferences:(id)arg1;
@property(nonatomic, readonly) double progress;
- (void)primitiveInvalidate;

@end

