//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEFoundation/_TtC13IDEFoundation23IDEDocumentationManager.h>

@class IDEIndex;

__attribute__((visibility("hidden")))
@interface _TtC13IDEFoundation36_IDEDocumentationManagerForWorkspace : _TtC13IDEFoundation23IDEDocumentationManager
{
    // Error parsing type: , name: _index
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)primitiveInvalidate;
- (id)initWithWorkspace:(id)arg1;
@property(nonatomic, retain) IDEIndex *_index; // @synthesize _index;

@end

