//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEFoundation/_TtC13IDEFoundation37IDEStructureEditingInsertingProcedure.h>

@class NSString;

@interface _TtC13IDEFoundation39IDEStructureEditingMoveToGroupProcedure : _TtC13IDEFoundation37IDEStructureEditingInsertingProcedure
{
    // Error parsing type: , name: _completionBlock
}

- (CDUnknownBlockType).cxx_destruct;
- (void)startOperationOnQueue:(id)arg1 finalOperation:(id)arg2;
@property(nonatomic, readonly) NSString *title;
- (void)primitiveInvalidate;

@end

