//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEFoundation/_TtC13IDEFoundation35IDEStructureEditingPlannedProcedure.h>

@class IDEGroup;

@interface _TtC13IDEFoundation37IDEStructureEditingInsertingProcedure : _TtC13IDEFoundation35IDEStructureEditingPlannedProcedure
{
    // Error parsing type: , name: insertionPlan
    // Error parsing type: , name: destinationGroup
}

- (CDUnknownBlockType).cxx_destruct;
@property(nonatomic, readonly) IDEGroup *destinationGroup; // @synthesize destinationGroup;

@end

