//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTPortal/DVTPortalProfile.h>

@interface DVTPortalProfile (IDEQualifiableProfile)
- (BOOL)isXcodeManaged;
- (id)provisioningProfilePlatformIdentifier;
- (BOOL)matchesBundleIdentifier:(id)arg1;
- (BOOL)expired;
- (id)appIdentifierUserDescription;
- (id)teamName;
- (id)teamID;
@end

