//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSDate, NSString;

@protocol DVTQualifiableProfile
@property(readonly) BOOL isActive;
@property(readonly) BOOL expired;
@property(readonly) NSDate *expirationDate;
@property(readonly) NSString *appIdentifierUserDescription;
@property(readonly) NSString *provisioningProfilePlatformIdentifier;
@property(readonly) NSString *teamName;
@property(readonly) NSString *teamID;
@property(readonly) NSString *name;
- (BOOL)isXcodeManaged;
- (BOOL)matchesBundleIdentifier:(NSString *)arg1;

@optional
- (BOOL)isAppleInternal;
@end

