//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEFoundation/IDEBatchFindFilePathPredicate.h>

@interface IDEBatchFindSCMStatusPredicate : IDEBatchFindFilePathPredicate
{
    long long _desiredStatus;
}

+ (id)propertyListIdentifier;
+ (id)decodeFromPropertyListRepresentation:(id)arg1;
@property(readonly) long long desiredStatus; // @synthesize desiredStatus=_desiredStatus;
- (BOOL)isWorkspaceSpecific;
- (id)propertyListRepresentation;
- (CDUnknownBlockType)filterBoundToWorkspace:(id)arg1;
- (BOOL)isEqualToFilePathPredicateWithIdenticalClass:(id)arg1;
- (unsigned long long)hash;
- (id)initWithDesiredStatus:(long long)arg1;

@end

