//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class DVTSourceFileLineCoverageData, NSArray;

@interface IDECoverageAnnotationLineCoverage : NSObject
{
    unsigned long long _lineCoverageType;
    long long _lineNumber;
    long long _executionCount;
    DVTSourceFileLineCoverageData *_lineCoverageData;
    NSArray *_subranges;
}

@property(copy, nonatomic) NSArray *subranges; // @synthesize subranges=_subranges;
@property(retain, nonatomic) DVTSourceFileLineCoverageData *lineCoverageData; // @synthesize lineCoverageData=_lineCoverageData;
@property(nonatomic) long long executionCount; // @synthesize executionCount=_executionCount;
@property(nonatomic) long long lineNumber; // @synthesize lineNumber=_lineNumber;
@property(nonatomic) unsigned long long lineCoverageType; // @synthesize lineCoverageType=_lineCoverageType;
- (void).cxx_destruct;
- (id)description;

@end

