//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSIndexSet;

@interface IDECoverageAnnotationLineCoverageRange : NSObject
{
    long long _executionCount;
    NSIndexSet *_lineIndexes;
    unsigned long long _lineCoverageType;
    NSArray *_subranges;
}

@property(copy, nonatomic) NSArray *subranges; // @synthesize subranges=_subranges;
@property(nonatomic) unsigned long long lineCoverageType; // @synthesize lineCoverageType=_lineCoverageType;
@property(copy, nonatomic) NSIndexSet *lineIndexes; // @synthesize lineIndexes=_lineIndexes;
@property(nonatomic) long long executionCount; // @synthesize executionCount=_executionCount;
- (void).cxx_destruct;
- (id)description;

@end

