//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEFoundation/IDELocalizationWorkContext.h>

@class NSData, NSURL;

@interface IDELocalizationWorkWriteData : IDELocalizationWorkContext
{
}

+ (id)contextWithParent:(id)arg1 data:(id)arg2 url:(id)arg3;
@property(readonly, copy) NSURL *url;
@property(readonly, copy) NSData *data;

@end

