//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEFoundation/IDELocalizationWorkContext.h>

@class DVTFilePath, DVTLocale, IDEContainer, IDEGroup;
@protocol IDELocalizedContainer, IDELocalizedGroup;

@interface IDELocalizationWorkAddFileReference : IDELocalizationWorkContext
{
    IDEContainer<IDELocalizedContainer> *_container;
    IDEGroup<IDELocalizedGroup> *_group;
    DVTLocale *_locale;
    DVTFilePath *_filePath;
}

@property(copy, nonatomic) DVTFilePath *filePath; // @synthesize filePath=_filePath;
@property(copy, nonatomic) DVTLocale *locale; // @synthesize locale=_locale;
@property(retain, nonatomic) IDEGroup<IDELocalizedGroup> *group; // @synthesize group=_group;
@property(retain, nonatomic) IDEContainer<IDELocalizedContainer> *container; // @synthesize container=_container;
- (void).cxx_destruct;
- (void)primitiveInvalidate;

@end

