//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEFoundation/IDELocalizationWorkContext.h>

#import <IDEFoundation/IDELocalizationWorkProvider-Protocol.h>

@class IDEContainer, NSDictionary, NSMutableDictionary, NSString;
@protocol IDELocalizedContainer;

@interface IDELocalizedResourcePopulationContext : IDELocalizationWorkContext <IDELocalizationWorkProvider>
{
    NSMutableDictionary *_adaptorsByGroupIdentifier;
    IDEContainer<IDELocalizedContainer> *_container;
}

+ (id)contextWithParent:(id)arg1 container:(id)arg2;
@property(retain) IDEContainer<IDELocalizedContainer> *container; // @synthesize container=_container;
@property(readonly) NSDictionary *adaptorsByGroupIdentifier; // @synthesize adaptorsByGroupIdentifier=_adaptorsByGroupIdentifier;
- (void).cxx_destruct;
- (id)work;
- (void)primitiveInvalidate;
- (void)setAdaptor:(id)arg1 forGroupIdentifier:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

