//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEFoundation/IDELocalizationWorkContext.h>

@class NSArray, NSNumber, NSString;

@interface IDELocalizationWorkExtractLocStrings : IDELocalizationWorkContext
{
}

+ (id)contextWithParent:(id)arg1 sourceFiles:(id)arg2 temporaryDirectory:(id)arg3;
@property(readonly, copy) NSNumber *signalStatus;
@property(readonly, copy) NSNumber *exitStatus;
@property(readonly, copy) NSString *temporaryDirectory;
@property(readonly, copy) NSArray *sourceFiles;

@end

