//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEFoundation/IDEOpenQuicklyAbstractWorkspaceResultAggregator.h>

@interface IDEOpenQuicklySDKFilePathAggregator : IDEOpenQuicklyAbstractWorkspaceResultAggregator
{
}

+ (long long)aggregationCutoff;
- (id)transformAggregateResults:(id)arg1;
- (void)generateGeneratorsWithCompletionGroup:(id)arg1 forWorkspace:(id)arg2;

@end

