//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEFoundation/IDEProvisioningUserAction.h>

@protocol DVTProvisioningProfile;

@interface IDEProvisioningInstallProfileUserAction : IDEProvisioningUserAction
{
    id <DVTProvisioningProfile> _profile;
}

@property(readonly) id <DVTProvisioningProfile> profile; // @synthesize profile=_profile;
- (void).cxx_destruct;
- (BOOL)supportsBatchAuthorization;
- (id)userActionName;
- (id)userActionMessage;
- (id)userActionTitle;
- (id)initWithProfile:(id)arg1 context:(id)arg2;

@end

