//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface IDEProvisioningEntitlementsOverrides : NSObject
{
    NSString *_appIdentifierPrefix;
    NSString *_teamIdentifierPrefix;
    NSString *_bundleIdentifier;
}

@property(retain, nonatomic) NSString *bundleIdentifier; // @synthesize bundleIdentifier=_bundleIdentifier;
@property(retain, nonatomic) NSString *teamIdentifierPrefix; // @synthesize teamIdentifierPrefix=_teamIdentifierPrefix;
@property(retain, nonatomic) NSString *appIdentifierPrefix; // @synthesize appIdentifierPrefix=_appIdentifierPrefix;
- (void).cxx_destruct;
- (id)description;

@end

