//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEFoundation/IDEUpgradeContext.h>

@class IDEScheme;

@interface IDEUpgradeSchemeContext : IDEUpgradeContext
{
    IDEScheme *_scheme;
}

@property(readonly) IDEScheme *scheme; // @synthesize scheme=_scheme;
- (void).cxx_destruct;
- (id)description;
- (id)initWithScheme:(id)arg1;

@end

