//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IBFoundation/IBICFolder.h>

@interface IBICAbstractCatalog : IBICFolder
{
}

+ (id)contentReferenceTypeName;
+ (Class)requiredParentClass;
+ (id)catalogItemFileExtension;
+ (id)classNameComponents;
+ (id)createDefaultInstancesForUnitTesting;
- (id)classesForImportingLooseFilesInImportOrder;
- (BOOL)shouldShowSuggestionSetsForBundleIcons;
- (CDStruct_550fdc95)taggingSupport;
- (void)replaceChildrenWithDiskContent:(id)arg1;
- (id)allIconSets;
- (id)allImageSets;
- (id)catalog;

@end

