//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IBCocoaTouchToolFoundation/IBUISimulatedMetricChain.h>

@class IBUIMetricRepresentation;

@interface IBUISimulatedNavigationBarOverrideMetricChain : IBUISimulatedMetricChain
{
    BOOL _forcePrompt;
    IBUIMetricRepresentation *_navigationBar;
}

@property(readonly, nonatomic) BOOL forcePrompt; // @synthesize forcePrompt=_forcePrompt;
@property(readonly, nonatomic) IBUIMetricRepresentation *navigationBar; // @synthesize navigationBar=_navigationBar;
- (void).cxx_destruct;
- (void)encodeWithBinaryArchiver:(id)arg1;
- (id)initWithBinaryUnarchiver:(id)arg1;
- (id)initWithNavigationBar:(id)arg1 forcePrompt:(BOOL)arg2 precedingMetric:(id)arg3;

@end

