//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IBCocoaTouchToolFoundation/IBUISimulatedMetricChain.h>

@class IBUIMetricRepresentation;

@interface IBUISimulatedTabBarOverrideMetricChain : IBUISimulatedMetricChain
{
    IBUIMetricRepresentation *_tabBar;
}

@property(readonly, nonatomic) IBUIMetricRepresentation *tabBar; // @synthesize tabBar=_tabBar;
- (void).cxx_destruct;
- (void)encodeWithBinaryArchiver:(id)arg1;
- (id)initWithBinaryUnarchiver:(id)arg1;
- (id)initWithTabBar:(id)arg1 precedingMetric:(id)arg2;

@end

